### ISSUE TITLE
创建国信 OEM 分支

### ISSUE THREAD

**Issue by joyme123** [caicloud/charts#238]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

基于标准产品2.10.0，tag 是 v1.4.4，创建国信的 oem 的分支 guosen。

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by qianlei90** [comment]
`cps-2.10/guosen` @joyme123 
/close
